export const GET_ALL_POLLS_LOADING = 'GET_ALL_POLLS_LOADING';
export const GET_ALL_POLLS_SUCCESS = 'GET_ALL_POLLS_SUCCESS';
export const GET_ALL_POLLS_ERROR = 'GET_ALL_POLLS_ERROR';

export const GET_SINGLE_POLL_LOADING = 'GET_SINGLE_POLL_LOADING';
export const GET_SINGLE_POLL_SUCCESS = 'GET_SINGLE_POLL_SUCCESS';
export const GET_SINGLE_POLL_ERROR = 'GET_SINGLE_POLL_ERROR';
